apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yogbot
  namespace: yogbot
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: yogbot
        image: yogstation/yogbot:$BUILD_NUMBER